const { withAppBuildGradle } = require("expo/config-plugins");

const marker = "// @generated by withStandaloneApk";

module.exports = function withStandaloneApk(config) {
  return withAppBuildGradle(config, (gradleConfig) => {
    let contents = gradleConfig.modResults.contents;

    if (!contents.includes(marker)) {
      contents = contents.replace(
        "react {",
        `react {\n    ${marker}\n    // Bundle JavaScript into the CI-built APK instead of requiring Metro.\n    debuggableVariants = []`,
      );

      contents = contents.replace(
        /debug \{\s+signingConfig signingConfigs\.debug\s+\}/,
        `debug {\n            signingConfig signingConfigs.debug\n            // Disable React Native developer support for the standalone test APK.\n            debuggable false\n        }`,
      );
    }

    if (!contents.includes("K4Y_KEYSTORE_PATH")) {
      contents = contents.replace(
        "signingConfigs {\n        debug {",
        `signingConfigs {
        release {
            def keystorePath = System.getenv("K4Y_KEYSTORE_PATH")
            if (keystorePath) {
                storeFile file(keystorePath)
                storePassword System.getenv("K4Y_KEYSTORE_PASSWORD")
                keyAlias System.getenv("K4Y_KEY_ALIAS")
                keyPassword System.getenv("K4Y_KEY_PASSWORD")
            }
        }
        debug {`,
      );

      contents = contents.replace(
        /release \{\s+\/\/ Caution![\s\S]*?signingConfig signingConfigs\.debug/,
        `release {
            // CI uses the permanent Kuryr4You release key. Local builds safely
            // fall back to the debug key unless signing variables are set.
            signingConfig System.getenv("K4Y_KEYSTORE_PATH") ? signingConfigs.release : signingConfigs.debug`,
      );
    }

    gradleConfig.modResults.contents = contents;
    return gradleConfig;
  });
};
