const { withAppBuildGradle } = require("expo/config-plugins");

const marker = "// @generated by withStandaloneApk";

module.exports = function withStandaloneApk(config) {
  return withAppBuildGradle(config, (gradleConfig) => {
    let contents = gradleConfig.modResults.contents;

    if (!contents.includes(marker)) {
      contents = contents.replace(
        "react {",
        `react {\n    ${marker}\n    // Bundle JavaScript into the CI-built APK instead of requiring Metro.\n    debuggableVariants = []`,
      );

      contents = contents.replace(
        /debug \{\s+signingConfig signingConfigs\.debug\s+\}/,
        `debug {\n            signingConfig signingConfigs.debug\n            // Disable developer support in the standalone test APK.\n            debuggable false\n        }`,
      );
    }

    gradleConfig.modResults.contents = contents;
    return gradleConfig;
  });
};
