/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZakaznikRouteImport } from './routes/zakaznik'
import { Route as RidicRouteImport } from './routes/ridic'
import { Route as RegistraceRouteImport } from './routes/registrace'
import { Route as PrihlaseniRouteImport } from './routes/prihlaseni'
import { Route as PlatbaUspesnaRouteImport } from './routes/platba-uspesna'
import { Route as ObjednatRouteImport } from './routes/objednat'
import { Route as MockupLightRouteImport } from './routes/mockup-light'
import { Route as MockupRouteImport } from './routes/mockup'
import { Route as JakToFungujeRouteImport } from './routes/jak-to-funguje'
import { Route as DokoncitRegistraciRouteImport } from './routes/dokoncit-registraci'
import { Route as DispatcerRouteImport } from './routes/dispatcer'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZakaznikIndexRouteImport } from './routes/zakaznik.index'
import { Route as RidicIndexRouteImport } from './routes/ridic.index'
import { Route as DispatcerIndexRouteImport } from './routes/dispatcer.index'
import { Route as ZakaznikZasilkyRouteImport } from './routes/zakaznik.zasilky'
import { Route as ZakaznikUctenkyRouteImport } from './routes/zakaznik.uctenky'
import { Route as ZakaznikProfilRouteImport } from './routes/zakaznik.profil'
import { Route as ZakaznikNovaZasilkaRouteImport } from './routes/zakaznik.nova-zasilka'
import { Route as ZakaznikFakturyRouteImport } from './routes/zakaznik.faktury'
import { Route as SledovaniTokenRouteImport } from './routes/sledovani.$token'
import { Route as RidicZakazkyRouteImport } from './routes/ridic.zakazky'
import { Route as RidicProfilRouteImport } from './routes/ridic.profil'
import { Route as RidicGpsRouteImport } from './routes/ridic.gps'
import { Route as RidicDostupnostRouteImport } from './routes/ridic.dostupnost'
import { Route as DispatcerZasilkyRouteImport } from './routes/dispatcer.zasilky'
import { Route as DispatcerZamestnanciRouteImport } from './routes/dispatcer.zamestnanci'
import { Route as DispatcerUzivateleRouteImport } from './routes/dispatcer.uzivatele'
import { Route as DispatcerTymyRouteImport } from './routes/dispatcer.tymy'
import { Route as DispatcerStatistikyRouteImport } from './routes/dispatcer.statistiky'
import { Route as DispatcerNastaveniRouteImport } from './routes/dispatcer.nastaveni'
import { Route as DispatcerMapaRouteImport } from './routes/dispatcer.mapa'
import { Route as DispatcerKalendarRouteImport } from './routes/dispatcer.kalendar'
import { Route as DispatcerFakturaceRouteImport } from './routes/dispatcer.fakturace'
import { Route as DispatcerCrmRouteImport } from './routes/dispatcer.crm'
import { Route as RidicPodRideIdRouteImport } from './routes/ridic.pod.$rideId'
import { Route as DispatcerZamestnanciEmployeeIdRouteImport } from './routes/dispatcer.zamestnanci.$employeeId'
import { Route as DispatcerCrmContactIdRouteImport } from './routes/dispatcer.crm.$contactId'

const ZakaznikRoute = ZakaznikRouteImport.update({
  id: '/zakaznik',
  path: '/zakaznik',
  getParentRoute: () => rootRouteImport,
} as any)
const RidicRoute = RidicRouteImport.update({
  id: '/ridic',
  path: '/ridic',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistraceRoute = RegistraceRouteImport.update({
  id: '/registrace',
  path: '/registrace',
  getParentRoute: () => rootRouteImport,
} as any)
const PrihlaseniRoute = PrihlaseniRouteImport.update({
  id: '/prihlaseni',
  path: '/prihlaseni',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatbaUspesnaRoute = PlatbaUspesnaRouteImport.update({
  id: '/platba-uspesna',
  path: '/platba-uspesna',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjednatRoute = ObjednatRouteImport.update({
  id: '/objednat',
  path: '/objednat',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupLightRoute = MockupLightRouteImport.update({
  id: '/mockup-light',
  path: '/mockup-light',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupRoute = MockupRouteImport.update({
  id: '/mockup',
  path: '/mockup',
  getParentRoute: () => rootRouteImport,
} as any)
const JakToFungujeRoute = JakToFungujeRouteImport.update({
  id: '/jak-to-funguje',
  path: '/jak-to-funguje',
  getParentRoute: () => rootRouteImport,
} as any)
const DokoncitRegistraciRoute = DokoncitRegistraciRouteImport.update({
  id: '/dokoncit-registraci',
  path: '/dokoncit-registraci',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatcerRoute = DispatcerRouteImport.update({
  id: '/dispatcer',
  path: '/dispatcer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakaznikIndexRoute = ZakaznikIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZakaznikRoute,
} as any)
const RidicIndexRoute = RidicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RidicRoute,
} as any)
const DispatcerIndexRoute = DispatcerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DispatcerRoute,
} as any)
const ZakaznikZasilkyRoute = ZakaznikZasilkyRouteImport.update({
  id: '/zasilky',
  path: '/zasilky',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikUctenkyRoute = ZakaznikUctenkyRouteImport.update({
  id: '/uctenky',
  path: '/uctenky',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikProfilRoute = ZakaznikProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikNovaZasilkaRoute = ZakaznikNovaZasilkaRouteImport.update({
  id: '/nova-zasilka',
  path: '/nova-zasilka',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikFakturyRoute = ZakaznikFakturyRouteImport.update({
  id: '/faktury',
  path: '/faktury',
  getParentRoute: () => ZakaznikRoute,
} as any)
const SledovaniTokenRoute = SledovaniTokenRouteImport.update({
  id: '/sledovani/$token',
  path: '/sledovani/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RidicZakazkyRoute = RidicZakazkyRouteImport.update({
  id: '/zakazky',
  path: '/zakazky',
  getParentRoute: () => RidicRoute,
} as any)
const RidicProfilRoute = RidicProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => RidicRoute,
} as any)
const RidicGpsRoute = RidicGpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => RidicRoute,
} as any)
const RidicDostupnostRoute = RidicDostupnostRouteImport.update({
  id: '/dostupnost',
  path: '/dostupnost',
  getParentRoute: () => RidicRoute,
} as any)
const DispatcerZasilkyRoute = DispatcerZasilkyRouteImport.update({
  id: '/zasilky',
  path: '/zasilky',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerZamestnanciRoute = DispatcerZamestnanciRouteImport.update({
  id: '/zamestnanci',
  path: '/zamestnanci',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerUzivateleRoute = DispatcerUzivateleRouteImport.update({
  id: '/uzivatele',
  path: '/uzivatele',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerTymyRoute = DispatcerTymyRouteImport.update({
  id: '/tymy',
  path: '/tymy',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerStatistikyRoute = DispatcerStatistikyRouteImport.update({
  id: '/statistiky',
  path: '/statistiky',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerNastaveniRoute = DispatcerNastaveniRouteImport.update({
  id: '/nastaveni',
  path: '/nastaveni',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerMapaRoute = DispatcerMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerKalendarRoute = DispatcerKalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerFakturaceRoute = DispatcerFakturaceRouteImport.update({
  id: '/fakturace',
  path: '/fakturace',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerCrmRoute = DispatcerCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DispatcerRoute,
} as any)
const RidicPodRideIdRoute = RidicPodRideIdRouteImport.update({
  id: '/pod/$rideId',
  path: '/pod/$rideId',
  getParentRoute: () => RidicRoute,
} as any)
const DispatcerZamestnanciEmployeeIdRoute =
  DispatcerZamestnanciEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => DispatcerZamestnanciRoute,
  } as any)
const DispatcerCrmContactIdRoute = DispatcerCrmContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => DispatcerCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dispatcer': typeof DispatcerRouteWithChildren
  '/dokoncit-registraci': typeof DokoncitRegistraciRoute
  '/jak-to-funguje': typeof JakToFungujeRoute
  '/mockup': typeof MockupRoute
  '/mockup-light': typeof MockupLightRoute
  '/objednat': typeof ObjednatRoute
  '/platba-uspesna': typeof PlatbaUspesnaRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/ridic': typeof RidicRouteWithChildren
  '/zakaznik': typeof ZakaznikRouteWithChildren
  '/dispatcer/crm': typeof DispatcerCrmRouteWithChildren
  '/dispatcer/fakturace': typeof DispatcerFakturaceRoute
  '/dispatcer/kalendar': typeof DispatcerKalendarRoute
  '/dispatcer/mapa': typeof DispatcerMapaRoute
  '/dispatcer/nastaveni': typeof DispatcerNastaveniRoute
  '/dispatcer/statistiky': typeof DispatcerStatistikyRoute
  '/dispatcer/tymy': typeof DispatcerTymyRoute
  '/dispatcer/uzivatele': typeof DispatcerUzivateleRoute
  '/dispatcer/zamestnanci': typeof DispatcerZamestnanciRouteWithChildren
  '/dispatcer/zasilky': typeof DispatcerZasilkyRoute
  '/ridic/dostupnost': typeof RidicDostupnostRoute
  '/ridic/gps': typeof RidicGpsRoute
  '/ridic/profil': typeof RidicProfilRoute
  '/ridic/zakazky': typeof RidicZakazkyRoute
  '/sledovani/$token': typeof SledovaniTokenRoute
  '/zakaznik/faktury': typeof ZakaznikFakturyRoute
  '/zakaznik/nova-zasilka': typeof ZakaznikNovaZasilkaRoute
  '/zakaznik/profil': typeof ZakaznikProfilRoute
  '/zakaznik/uctenky': typeof ZakaznikUctenkyRoute
  '/zakaznik/zasilky': typeof ZakaznikZasilkyRoute
  '/dispatcer/': typeof DispatcerIndexRoute
  '/ridic/': typeof RidicIndexRoute
  '/zakaznik/': typeof ZakaznikIndexRoute
  '/dispatcer/crm/$contactId': typeof DispatcerCrmContactIdRoute
  '/dispatcer/zamestnanci/$employeeId': typeof DispatcerZamestnanciEmployeeIdRoute
  '/ridic/pod/$rideId': typeof RidicPodRideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dokoncit-registraci': typeof DokoncitRegistraciRoute
  '/jak-to-funguje': typeof JakToFungujeRoute
  '/mockup': typeof MockupRoute
  '/mockup-light': typeof MockupLightRoute
  '/objednat': typeof ObjednatRoute
  '/platba-uspesna': typeof PlatbaUspesnaRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/dispatcer/crm': typeof DispatcerCrmRouteWithChildren
  '/dispatcer/fakturace': typeof DispatcerFakturaceRoute
  '/dispatcer/kalendar': typeof DispatcerKalendarRoute
  '/dispatcer/mapa': typeof DispatcerMapaRoute
  '/dispatcer/nastaveni': typeof DispatcerNastaveniRoute
  '/dispatcer/statistiky': typeof DispatcerStatistikyRoute
  '/dispatcer/tymy': typeof DispatcerTymyRoute
  '/dispatcer/uzivatele': typeof DispatcerUzivateleRoute
  '/dispatcer/zamestnanci': typeof DispatcerZamestnanciRouteWithChildren
  '/dispatcer/zasilky': typeof DispatcerZasilkyRoute
  '/ridic/dostupnost': typeof RidicDostupnostRoute
  '/ridic/gps': typeof RidicGpsRoute
  '/ridic/profil': typeof RidicProfilRoute
  '/ridic/zakazky': typeof RidicZakazkyRoute
  '/sledovani/$token': typeof SledovaniTokenRoute
  '/zakaznik/faktury': typeof ZakaznikFakturyRoute
  '/zakaznik/nova-zasilka': typeof ZakaznikNovaZasilkaRoute
  '/zakaznik/profil': typeof ZakaznikProfilRoute
  '/zakaznik/uctenky': typeof ZakaznikUctenkyRoute
  '/zakaznik/zasilky': typeof ZakaznikZasilkyRoute
  '/dispatcer': typeof DispatcerIndexRoute
  '/ridic': typeof RidicIndexRoute
  '/zakaznik': typeof ZakaznikIndexRoute
  '/dispatcer/crm/$contactId': typeof DispatcerCrmContactIdRoute
  '/dispatcer/zamestnanci/$employeeId': typeof DispatcerZamestnanciEmployeeIdRoute
  '/ridic/pod/$rideId': typeof RidicPodRideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dispatcer': typeof DispatcerRouteWithChildren
  '/dokoncit-registraci': typeof DokoncitRegistraciRoute
  '/jak-to-funguje': typeof JakToFungujeRoute
  '/mockup': typeof MockupRoute
  '/mockup-light': typeof MockupLightRoute
  '/objednat': typeof ObjednatRoute
  '/platba-uspesna': typeof PlatbaUspesnaRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/ridic': typeof RidicRouteWithChildren
  '/zakaznik': typeof ZakaznikRouteWithChildren
  '/dispatcer/crm': typeof DispatcerCrmRouteWithChildren
  '/dispatcer/fakturace': typeof DispatcerFakturaceRoute
  '/dispatcer/kalendar': typeof DispatcerKalendarRoute
  '/dispatcer/mapa': typeof DispatcerMapaRoute
  '/dispatcer/nastaveni': typeof DispatcerNastaveniRoute
  '/dispatcer/statistiky': typeof DispatcerStatistikyRoute
  '/dispatcer/tymy': typeof DispatcerTymyRoute
  '/dispatcer/uzivatele': typeof DispatcerUzivateleRoute
  '/dispatcer/zamestnanci': typeof DispatcerZamestnanciRouteWithChildren
  '/dispatcer/zasilky': typeof DispatcerZasilkyRoute
  '/ridic/dostupnost': typeof RidicDostupnostRoute
  '/ridic/gps': typeof RidicGpsRoute
  '/ridic/profil': typeof RidicProfilRoute
  '/ridic/zakazky': typeof RidicZakazkyRoute
  '/sledovani/$token': typeof SledovaniTokenRoute
  '/zakaznik/faktury': typeof ZakaznikFakturyRoute
  '/zakaznik/nova-zasilka': typeof ZakaznikNovaZasilkaRoute
  '/zakaznik/profil': typeof ZakaznikProfilRoute
  '/zakaznik/uctenky': typeof ZakaznikUctenkyRoute
  '/zakaznik/zasilky': typeof ZakaznikZasilkyRoute
  '/dispatcer/': typeof DispatcerIndexRoute
  '/ridic/': typeof RidicIndexRoute
  '/zakaznik/': typeof ZakaznikIndexRoute
  '/dispatcer/crm/$contactId': typeof DispatcerCrmContactIdRoute
  '/dispatcer/zamestnanci/$employeeId': typeof DispatcerZamestnanciEmployeeIdRoute
  '/ridic/pod/$rideId': typeof RidicPodRideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/dispatcer'
    | '/dokoncit-registraci'
    | '/jak-to-funguje'
    | '/mockup'
    | '/mockup-light'
    | '/objednat'
    | '/platba-uspesna'
    | '/prihlaseni'
    | '/registrace'
    | '/ridic'
    | '/zakaznik'
    | '/dispatcer/crm'
    | '/dispatcer/fakturace'
    | '/dispatcer/kalendar'
    | '/dispatcer/mapa'
    | '/dispatcer/nastaveni'
    | '/dispatcer/statistiky'
    | '/dispatcer/tymy'
    | '/dispatcer/uzivatele'
    | '/dispatcer/zamestnanci'
    | '/dispatcer/zasilky'
    | '/ridic/dostupnost'
    | '/ridic/gps'
    | '/ridic/profil'
    | '/ridic/zakazky'
    | '/sledovani/$token'
    | '/zakaznik/faktury'
    | '/zakaznik/nova-zasilka'
    | '/zakaznik/profil'
    | '/zakaznik/uctenky'
    | '/zakaznik/zasilky'
    | '/dispatcer/'
    | '/ridic/'
    | '/zakaznik/'
    | '/dispatcer/crm/$contactId'
    | '/dispatcer/zamestnanci/$employeeId'
    | '/ridic/pod/$rideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/dokoncit-registraci'
    | '/jak-to-funguje'
    | '/mockup'
    | '/mockup-light'
    | '/objednat'
    | '/platba-uspesna'
    | '/prihlaseni'
    | '/registrace'
    | '/dispatcer/crm'
    | '/dispatcer/fakturace'
    | '/dispatcer/kalendar'
    | '/dispatcer/mapa'
    | '/dispatcer/nastaveni'
    | '/dispatcer/statistiky'
    | '/dispatcer/tymy'
    | '/dispatcer/uzivatele'
    | '/dispatcer/zamestnanci'
    | '/dispatcer/zasilky'
    | '/ridic/dostupnost'
    | '/ridic/gps'
    | '/ridic/profil'
    | '/ridic/zakazky'
    | '/sledovani/$token'
    | '/zakaznik/faktury'
    | '/zakaznik/nova-zasilka'
    | '/zakaznik/profil'
    | '/zakaznik/uctenky'
    | '/zakaznik/zasilky'
    | '/dispatcer'
    | '/ridic'
    | '/zakaznik'
    | '/dispatcer/crm/$contactId'
    | '/dispatcer/zamestnanci/$employeeId'
    | '/ridic/pod/$rideId'
  id:
    | '__root__'
    | '/'
    | '/admin-setup'
    | '/dispatcer'
    | '/dokoncit-registraci'
    | '/jak-to-funguje'
    | '/mockup'
    | '/mockup-light'
    | '/objednat'
    | '/platba-uspesna'
    | '/prihlaseni'
    | '/registrace'
    | '/ridic'
    | '/zakaznik'
    | '/dispatcer/crm'
    | '/dispatcer/fakturace'
    | '/dispatcer/kalendar'
    | '/dispatcer/mapa'
    | '/dispatcer/nastaveni'
    | '/dispatcer/statistiky'
    | '/dispatcer/tymy'
    | '/dispatcer/uzivatele'
    | '/dispatcer/zamestnanci'
    | '/dispatcer/zasilky'
    | '/ridic/dostupnost'
    | '/ridic/gps'
    | '/ridic/profil'
    | '/ridic/zakazky'
    | '/sledovani/$token'
    | '/zakaznik/faktury'
    | '/zakaznik/nova-zasilka'
    | '/zakaznik/profil'
    | '/zakaznik/uctenky'
    | '/zakaznik/zasilky'
    | '/dispatcer/'
    | '/ridic/'
    | '/zakaznik/'
    | '/dispatcer/crm/$contactId'
    | '/dispatcer/zamestnanci/$employeeId'
    | '/ridic/pod/$rideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSetupRoute: typeof AdminSetupRoute
  DispatcerRoute: typeof DispatcerRouteWithChildren
  DokoncitRegistraciRoute: typeof DokoncitRegistraciRoute
  JakToFungujeRoute: typeof JakToFungujeRoute
  MockupRoute: typeof MockupRoute
  MockupLightRoute: typeof MockupLightRoute
  ObjednatRoute: typeof ObjednatRoute
  PlatbaUspesnaRoute: typeof PlatbaUspesnaRoute
  PrihlaseniRoute: typeof PrihlaseniRoute
  RegistraceRoute: typeof RegistraceRoute
  RidicRoute: typeof RidicRouteWithChildren
  ZakaznikRoute: typeof ZakaznikRouteWithChildren
  SledovaniTokenRoute: typeof SledovaniTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zakaznik': {
      id: '/zakaznik'
      path: '/zakaznik'
      fullPath: '/zakaznik'
      preLoaderRoute: typeof ZakaznikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ridic': {
      id: '/ridic'
      path: '/ridic'
      fullPath: '/ridic'
      preLoaderRoute: typeof RidicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrace': {
      id: '/registrace'
      path: '/registrace'
      fullPath: '/registrace'
      preLoaderRoute: typeof RegistraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prihlaseni': {
      id: '/prihlaseni'
      path: '/prihlaseni'
      fullPath: '/prihlaseni'
      preLoaderRoute: typeof PrihlaseniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platba-uspesna': {
      id: '/platba-uspesna'
      path: '/platba-uspesna'
      fullPath: '/platba-uspesna'
      preLoaderRoute: typeof PlatbaUspesnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objednat': {
      id: '/objednat'
      path: '/objednat'
      fullPath: '/objednat'
      preLoaderRoute: typeof ObjednatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-light': {
      id: '/mockup-light'
      path: '/mockup-light'
      fullPath: '/mockup-light'
      preLoaderRoute: typeof MockupLightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup': {
      id: '/mockup'
      path: '/mockup'
      fullPath: '/mockup'
      preLoaderRoute: typeof MockupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jak-to-funguje': {
      id: '/jak-to-funguje'
      path: '/jak-to-funguje'
      fullPath: '/jak-to-funguje'
      preLoaderRoute: typeof JakToFungujeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokoncit-registraci': {
      id: '/dokoncit-registraci'
      path: '/dokoncit-registraci'
      fullPath: '/dokoncit-registraci'
      preLoaderRoute: typeof DokoncitRegistraciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatcer': {
      id: '/dispatcer'
      path: '/dispatcer'
      fullPath: '/dispatcer'
      preLoaderRoute: typeof DispatcerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakaznik/': {
      id: '/zakaznik/'
      path: '/'
      fullPath: '/zakaznik/'
      preLoaderRoute: typeof ZakaznikIndexRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/ridic/': {
      id: '/ridic/'
      path: '/'
      fullPath: '/ridic/'
      preLoaderRoute: typeof RidicIndexRouteImport
      parentRoute: typeof RidicRoute
    }
    '/dispatcer/': {
      id: '/dispatcer/'
      path: '/'
      fullPath: '/dispatcer/'
      preLoaderRoute: typeof DispatcerIndexRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/zakaznik/zasilky': {
      id: '/zakaznik/zasilky'
      path: '/zasilky'
      fullPath: '/zakaznik/zasilky'
      preLoaderRoute: typeof ZakaznikZasilkyRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/uctenky': {
      id: '/zakaznik/uctenky'
      path: '/uctenky'
      fullPath: '/zakaznik/uctenky'
      preLoaderRoute: typeof ZakaznikUctenkyRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/profil': {
      id: '/zakaznik/profil'
      path: '/profil'
      fullPath: '/zakaznik/profil'
      preLoaderRoute: typeof ZakaznikProfilRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/nova-zasilka': {
      id: '/zakaznik/nova-zasilka'
      path: '/nova-zasilka'
      fullPath: '/zakaznik/nova-zasilka'
      preLoaderRoute: typeof ZakaznikNovaZasilkaRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/faktury': {
      id: '/zakaznik/faktury'
      path: '/faktury'
      fullPath: '/zakaznik/faktury'
      preLoaderRoute: typeof ZakaznikFakturyRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/sledovani/$token': {
      id: '/sledovani/$token'
      path: '/sledovani/$token'
      fullPath: '/sledovani/$token'
      preLoaderRoute: typeof SledovaniTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ridic/zakazky': {
      id: '/ridic/zakazky'
      path: '/zakazky'
      fullPath: '/ridic/zakazky'
      preLoaderRoute: typeof RidicZakazkyRouteImport
      parentRoute: typeof RidicRoute
    }
    '/ridic/profil': {
      id: '/ridic/profil'
      path: '/profil'
      fullPath: '/ridic/profil'
      preLoaderRoute: typeof RidicProfilRouteImport
      parentRoute: typeof RidicRoute
    }
    '/ridic/gps': {
      id: '/ridic/gps'
      path: '/gps'
      fullPath: '/ridic/gps'
      preLoaderRoute: typeof RidicGpsRouteImport
      parentRoute: typeof RidicRoute
    }
    '/ridic/dostupnost': {
      id: '/ridic/dostupnost'
      path: '/dostupnost'
      fullPath: '/ridic/dostupnost'
      preLoaderRoute: typeof RidicDostupnostRouteImport
      parentRoute: typeof RidicRoute
    }
    '/dispatcer/zasilky': {
      id: '/dispatcer/zasilky'
      path: '/zasilky'
      fullPath: '/dispatcer/zasilky'
      preLoaderRoute: typeof DispatcerZasilkyRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/zamestnanci': {
      id: '/dispatcer/zamestnanci'
      path: '/zamestnanci'
      fullPath: '/dispatcer/zamestnanci'
      preLoaderRoute: typeof DispatcerZamestnanciRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/uzivatele': {
      id: '/dispatcer/uzivatele'
      path: '/uzivatele'
      fullPath: '/dispatcer/uzivatele'
      preLoaderRoute: typeof DispatcerUzivateleRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/tymy': {
      id: '/dispatcer/tymy'
      path: '/tymy'
      fullPath: '/dispatcer/tymy'
      preLoaderRoute: typeof DispatcerTymyRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/statistiky': {
      id: '/dispatcer/statistiky'
      path: '/statistiky'
      fullPath: '/dispatcer/statistiky'
      preLoaderRoute: typeof DispatcerStatistikyRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/nastaveni': {
      id: '/dispatcer/nastaveni'
      path: '/nastaveni'
      fullPath: '/dispatcer/nastaveni'
      preLoaderRoute: typeof DispatcerNastaveniRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/mapa': {
      id: '/dispatcer/mapa'
      path: '/mapa'
      fullPath: '/dispatcer/mapa'
      preLoaderRoute: typeof DispatcerMapaRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/kalendar': {
      id: '/dispatcer/kalendar'
      path: '/kalendar'
      fullPath: '/dispatcer/kalendar'
      preLoaderRoute: typeof DispatcerKalendarRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/fakturace': {
      id: '/dispatcer/fakturace'
      path: '/fakturace'
      fullPath: '/dispatcer/fakturace'
      preLoaderRoute: typeof DispatcerFakturaceRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/crm': {
      id: '/dispatcer/crm'
      path: '/crm'
      fullPath: '/dispatcer/crm'
      preLoaderRoute: typeof DispatcerCrmRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/ridic/pod/$rideId': {
      id: '/ridic/pod/$rideId'
      path: '/pod/$rideId'
      fullPath: '/ridic/pod/$rideId'
      preLoaderRoute: typeof RidicPodRideIdRouteImport
      parentRoute: typeof RidicRoute
    }
    '/dispatcer/zamestnanci/$employeeId': {
      id: '/dispatcer/zamestnanci/$employeeId'
      path: '/$employeeId'
      fullPath: '/dispatcer/zamestnanci/$employeeId'
      preLoaderRoute: typeof DispatcerZamestnanciEmployeeIdRouteImport
      parentRoute: typeof DispatcerZamestnanciRoute
    }
    '/dispatcer/crm/$contactId': {
      id: '/dispatcer/crm/$contactId'
      path: '/$contactId'
      fullPath: '/dispatcer/crm/$contactId'
      preLoaderRoute: typeof DispatcerCrmContactIdRouteImport
      parentRoute: typeof DispatcerCrmRoute
    }
  }
}

interface DispatcerCrmRouteChildren {
  DispatcerCrmContactIdRoute: typeof DispatcerCrmContactIdRoute
}

const DispatcerCrmRouteChildren: DispatcerCrmRouteChildren = {
  DispatcerCrmContactIdRoute: DispatcerCrmContactIdRoute,
}

const DispatcerCrmRouteWithChildren = DispatcerCrmRoute._addFileChildren(
  DispatcerCrmRouteChildren,
)

interface DispatcerZamestnanciRouteChildren {
  DispatcerZamestnanciEmployeeIdRoute: typeof DispatcerZamestnanciEmployeeIdRoute
}

const DispatcerZamestnanciRouteChildren: DispatcerZamestnanciRouteChildren = {
  DispatcerZamestnanciEmployeeIdRoute: DispatcerZamestnanciEmployeeIdRoute,
}

const DispatcerZamestnanciRouteWithChildren =
  DispatcerZamestnanciRoute._addFileChildren(DispatcerZamestnanciRouteChildren)

interface DispatcerRouteChildren {
  DispatcerCrmRoute: typeof DispatcerCrmRouteWithChildren
  DispatcerFakturaceRoute: typeof DispatcerFakturaceRoute
  DispatcerKalendarRoute: typeof DispatcerKalendarRoute
  DispatcerMapaRoute: typeof DispatcerMapaRoute
  DispatcerNastaveniRoute: typeof DispatcerNastaveniRoute
  DispatcerStatistikyRoute: typeof DispatcerStatistikyRoute
  DispatcerTymyRoute: typeof DispatcerTymyRoute
  DispatcerUzivateleRoute: typeof DispatcerUzivateleRoute
  DispatcerZamestnanciRoute: typeof DispatcerZamestnanciRouteWithChildren
  DispatcerZasilkyRoute: typeof DispatcerZasilkyRoute
  DispatcerIndexRoute: typeof DispatcerIndexRoute
}

const DispatcerRouteChildren: DispatcerRouteChildren = {
  DispatcerCrmRoute: DispatcerCrmRouteWithChildren,
  DispatcerFakturaceRoute: DispatcerFakturaceRoute,
  DispatcerKalendarRoute: DispatcerKalendarRoute,
  DispatcerMapaRoute: DispatcerMapaRoute,
  DispatcerNastaveniRoute: DispatcerNastaveniRoute,
  DispatcerStatistikyRoute: DispatcerStatistikyRoute,
  DispatcerTymyRoute: DispatcerTymyRoute,
  DispatcerUzivateleRoute: DispatcerUzivateleRoute,
  DispatcerZamestnanciRoute: DispatcerZamestnanciRouteWithChildren,
  DispatcerZasilkyRoute: DispatcerZasilkyRoute,
  DispatcerIndexRoute: DispatcerIndexRoute,
}

const DispatcerRouteWithChildren = DispatcerRoute._addFileChildren(
  DispatcerRouteChildren,
)

interface RidicRouteChildren {
  RidicDostupnostRoute: typeof RidicDostupnostRoute
  RidicGpsRoute: typeof RidicGpsRoute
  RidicProfilRoute: typeof RidicProfilRoute
  RidicZakazkyRoute: typeof RidicZakazkyRoute
  RidicIndexRoute: typeof RidicIndexRoute
  RidicPodRideIdRoute: typeof RidicPodRideIdRoute
}

const RidicRouteChildren: RidicRouteChildren = {
  RidicDostupnostRoute: RidicDostupnostRoute,
  RidicGpsRoute: RidicGpsRoute,
  RidicProfilRoute: RidicProfilRoute,
  RidicZakazkyRoute: RidicZakazkyRoute,
  RidicIndexRoute: RidicIndexRoute,
  RidicPodRideIdRoute: RidicPodRideIdRoute,
}

const RidicRouteWithChildren = RidicRoute._addFileChildren(RidicRouteChildren)

interface ZakaznikRouteChildren {
  ZakaznikFakturyRoute: typeof ZakaznikFakturyRoute
  ZakaznikNovaZasilkaRoute: typeof ZakaznikNovaZasilkaRoute
  ZakaznikProfilRoute: typeof ZakaznikProfilRoute
  ZakaznikUctenkyRoute: typeof ZakaznikUctenkyRoute
  ZakaznikZasilkyRoute: typeof ZakaznikZasilkyRoute
  ZakaznikIndexRoute: typeof ZakaznikIndexRoute
}

const ZakaznikRouteChildren: ZakaznikRouteChildren = {
  ZakaznikFakturyRoute: ZakaznikFakturyRoute,
  ZakaznikNovaZasilkaRoute: ZakaznikNovaZasilkaRoute,
  ZakaznikProfilRoute: ZakaznikProfilRoute,
  ZakaznikUctenkyRoute: ZakaznikUctenkyRoute,
  ZakaznikZasilkyRoute: ZakaznikZasilkyRoute,
  ZakaznikIndexRoute: ZakaznikIndexRoute,
}

const ZakaznikRouteWithChildren = ZakaznikRoute._addFileChildren(
  ZakaznikRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSetupRoute: AdminSetupRoute,
  DispatcerRoute: DispatcerRouteWithChildren,
  DokoncitRegistraciRoute: DokoncitRegistraciRoute,
  JakToFungujeRoute: JakToFungujeRoute,
  MockupRoute: MockupRoute,
  MockupLightRoute: MockupLightRoute,
  ObjednatRoute: ObjednatRoute,
  PlatbaUspesnaRoute: PlatbaUspesnaRoute,
  PrihlaseniRoute: PrihlaseniRoute,
  RegistraceRoute: RegistraceRoute,
  RidicRoute: RidicRouteWithChildren,
  ZakaznikRoute: ZakaznikRouteWithChildren,
  SledovaniTokenRoute: SledovaniTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
