/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZakaznikRouteImport } from './routes/zakaznik'
import { Route as VendingPortalRouteImport } from './routes/vending-portal'
import { Route as VendingRouteImport } from './routes/vending'
import { Route as RidicRouteImport } from './routes/ridic'
import { Route as RegistraceRouteImport } from './routes/registrace'
import { Route as PrihlaseniRouteImport } from './routes/prihlaseni'
import { Route as PlatbaUspesnaRouteImport } from './routes/platba-uspesna'
import { Route as OchranaSoukromiRouteImport } from './routes/ochrana-soukromi'
import { Route as ObjednatRouteImport } from './routes/objednat'
import { Route as MockupLightRouteImport } from './routes/mockup-light'
import { Route as MockupRouteImport } from './routes/mockup'
import { Route as JakToFungujeRouteImport } from './routes/jak-to-funguje'
import { Route as DokoncitRegistraciRouteImport } from './routes/dokoncit-registraci'
import { Route as DispatcerRouteImport } from './routes/dispatcer'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZakaznikIndexRouteImport } from './routes/zakaznik.index'
import { Route as VendingIndexRouteImport } from './routes/vending.index'
import { Route as VendingPortalIndexRouteImport } from './routes/vending-portal.index'
import { Route as RidicIndexRouteImport } from './routes/ridic.index'
import { Route as DispatcerIndexRouteImport } from './routes/dispatcer.index'
import { Route as ZakaznikZasilkyRouteImport } from './routes/zakaznik.zasilky'
import { Route as ZakaznikUctenkyRouteImport } from './routes/zakaznik.uctenky'
import { Route as ZakaznikSablonyRouteImport } from './routes/zakaznik.sablony'
import { Route as ZakaznikProfilRouteImport } from './routes/zakaznik.profil'
import { Route as ZakaznikNovaZasilkaRouteImport } from './routes/zakaznik.nova-zasilka'
import { Route as ZakaznikFakturyRouteImport } from './routes/zakaznik.faktury'
import { Route as VendingSablonyRouteImport } from './routes/vending.sablony'
import { Route as VendingNavstevyRouteImport } from './routes/vending.navstevy'
import { Route as VendingMapaRouteImport } from './routes/vending.mapa'
import { Route as VendingLokaceRouteImport } from './routes/vending.lokace'
import { Route as VendingKpiRouteImport } from './routes/vending.kpi'
import { Route as VendingKlientiRouteImport } from './routes/vending.klienti'
import { Route as VendingIncidentyRouteImport } from './routes/vending.incidenty'
import { Route as SledovaniTokenRouteImport } from './routes/sledovani.$token'
import { Route as RidicZakazkyRouteImport } from './routes/ridic.zakazky'
import { Route as RidicVendingRouteImport } from './routes/ridic.vending'
import { Route as RidicProfilRouteImport } from './routes/ridic.profil'
import { Route as RidicGpsRouteImport } from './routes/ridic.gps'
import { Route as RidicDostupnostRouteImport } from './routes/ridic.dostupnost'
import { Route as HodnoceniTokenRouteImport } from './routes/hodnoceni.$token'
import { Route as DispatcerZasilkyRouteImport } from './routes/dispatcer.zasilky'
import { Route as DispatcerZamestnanciRouteImport } from './routes/dispatcer.zamestnanci'
import { Route as DispatcerUzivateleRouteImport } from './routes/dispatcer.uzivatele'
import { Route as DispatcerTymyRouteImport } from './routes/dispatcer.tymy'
import { Route as DispatcerStatistikyRouteImport } from './routes/dispatcer.statistiky'
import { Route as DispatcerNastaveniRouteImport } from './routes/dispatcer.nastaveni'
import { Route as DispatcerMapaRouteImport } from './routes/dispatcer.mapa'
import { Route as DispatcerKalendarRouteImport } from './routes/dispatcer.kalendar'
import { Route as DispatcerFakturaceRouteImport } from './routes/dispatcer.fakturace'
import { Route as DispatcerCrmRouteImport } from './routes/dispatcer.crm'
import { Route as DispatcerArchivRouteImport } from './routes/dispatcer.archiv'
import { Route as DispatcerAiPristupRouteImport } from './routes/dispatcer.ai-pristup'
import { Route as RidicVendingIndexRouteImport } from './routes/ridic.vending.index'
import { Route as VendingNavstevyVisitIdRouteImport } from './routes/vending.navstevy.$visitId'
import { Route as VendingLokaceLocationIdRouteImport } from './routes/vending.lokace.$locationId'
import { Route as RidicVendingVisitIdRouteImport } from './routes/ridic.vending.$visitId'
import { Route as RidicPodRideIdRouteImport } from './routes/ridic.pod.$rideId'
import { Route as DispatcerZamestnanciEmployeeIdRouteImport } from './routes/dispatcer.zamestnanci.$employeeId'
import { Route as DispatcerCrmContactIdRouteImport } from './routes/dispatcer.crm.$contactId'

const ZakaznikRoute = ZakaznikRouteImport.update({
  id: '/zakaznik',
  path: '/zakaznik',
  getParentRoute: () => rootRouteImport,
} as any)
const VendingPortalRoute = VendingPortalRouteImport.update({
  id: '/vending-portal',
  path: '/vending-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const VendingRoute = VendingRouteImport.update({
  id: '/vending',
  path: '/vending',
  getParentRoute: () => rootRouteImport,
} as any)
const RidicRoute = RidicRouteImport.update({
  id: '/ridic',
  path: '/ridic',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistraceRoute = RegistraceRouteImport.update({
  id: '/registrace',
  path: '/registrace',
  getParentRoute: () => rootRouteImport,
} as any)
const PrihlaseniRoute = PrihlaseniRouteImport.update({
  id: '/prihlaseni',
  path: '/prihlaseni',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatbaUspesnaRoute = PlatbaUspesnaRouteImport.update({
  id: '/platba-uspesna',
  path: '/platba-uspesna',
  getParentRoute: () => rootRouteImport,
} as any)
const OchranaSoukromiRoute = OchranaSoukromiRouteImport.update({
  id: '/ochrana-soukromi',
  path: '/ochrana-soukromi',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjednatRoute = ObjednatRouteImport.update({
  id: '/objednat',
  path: '/objednat',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupLightRoute = MockupLightRouteImport.update({
  id: '/mockup-light',
  path: '/mockup-light',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupRoute = MockupRouteImport.update({
  id: '/mockup',
  path: '/mockup',
  getParentRoute: () => rootRouteImport,
} as any)
const JakToFungujeRoute = JakToFungujeRouteImport.update({
  id: '/jak-to-funguje',
  path: '/jak-to-funguje',
  getParentRoute: () => rootRouteImport,
} as any)
const DokoncitRegistraciRoute = DokoncitRegistraciRouteImport.update({
  id: '/dokoncit-registraci',
  path: '/dokoncit-registraci',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatcerRoute = DispatcerRouteImport.update({
  id: '/dispatcer',
  path: '/dispatcer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakaznikIndexRoute = ZakaznikIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZakaznikRoute,
} as any)
const VendingIndexRoute = VendingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendingRoute,
} as any)
const VendingPortalIndexRoute = VendingPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VendingPortalRoute,
} as any)
const RidicIndexRoute = RidicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RidicRoute,
} as any)
const DispatcerIndexRoute = DispatcerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DispatcerRoute,
} as any)
const ZakaznikZasilkyRoute = ZakaznikZasilkyRouteImport.update({
  id: '/zasilky',
  path: '/zasilky',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikUctenkyRoute = ZakaznikUctenkyRouteImport.update({
  id: '/uctenky',
  path: '/uctenky',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikSablonyRoute = ZakaznikSablonyRouteImport.update({
  id: '/sablony',
  path: '/sablony',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikProfilRoute = ZakaznikProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikNovaZasilkaRoute = ZakaznikNovaZasilkaRouteImport.update({
  id: '/nova-zasilka',
  path: '/nova-zasilka',
  getParentRoute: () => ZakaznikRoute,
} as any)
const ZakaznikFakturyRoute = ZakaznikFakturyRouteImport.update({
  id: '/faktury',
  path: '/faktury',
  getParentRoute: () => ZakaznikRoute,
} as any)
const VendingSablonyRoute = VendingSablonyRouteImport.update({
  id: '/sablony',
  path: '/sablony',
  getParentRoute: () => VendingRoute,
} as any)
const VendingNavstevyRoute = VendingNavstevyRouteImport.update({
  id: '/navstevy',
  path: '/navstevy',
  getParentRoute: () => VendingRoute,
} as any)
const VendingMapaRoute = VendingMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => VendingRoute,
} as any)
const VendingLokaceRoute = VendingLokaceRouteImport.update({
  id: '/lokace',
  path: '/lokace',
  getParentRoute: () => VendingRoute,
} as any)
const VendingKpiRoute = VendingKpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => VendingRoute,
} as any)
const VendingKlientiRoute = VendingKlientiRouteImport.update({
  id: '/klienti',
  path: '/klienti',
  getParentRoute: () => VendingRoute,
} as any)
const VendingIncidentyRoute = VendingIncidentyRouteImport.update({
  id: '/incidenty',
  path: '/incidenty',
  getParentRoute: () => VendingRoute,
} as any)
const SledovaniTokenRoute = SledovaniTokenRouteImport.update({
  id: '/sledovani/$token',
  path: '/sledovani/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RidicZakazkyRoute = RidicZakazkyRouteImport.update({
  id: '/zakazky',
  path: '/zakazky',
  getParentRoute: () => RidicRoute,
} as any)
const RidicVendingRoute = RidicVendingRouteImport.update({
  id: '/vending',
  path: '/vending',
  getParentRoute: () => RidicRoute,
} as any)
const RidicProfilRoute = RidicProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => RidicRoute,
} as any)
const RidicGpsRoute = RidicGpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => RidicRoute,
} as any)
const RidicDostupnostRoute = RidicDostupnostRouteImport.update({
  id: '/dostupnost',
  path: '/dostupnost',
  getParentRoute: () => RidicRoute,
} as any)
const HodnoceniTokenRoute = HodnoceniTokenRouteImport.update({
  id: '/hodnoceni/$token',
  path: '/hodnoceni/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatcerZasilkyRoute = DispatcerZasilkyRouteImport.update({
  id: '/zasilky',
  path: '/zasilky',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerZamestnanciRoute = DispatcerZamestnanciRouteImport.update({
  id: '/zamestnanci',
  path: '/zamestnanci',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerUzivateleRoute = DispatcerUzivateleRouteImport.update({
  id: '/uzivatele',
  path: '/uzivatele',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerTymyRoute = DispatcerTymyRouteImport.update({
  id: '/tymy',
  path: '/tymy',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerStatistikyRoute = DispatcerStatistikyRouteImport.update({
  id: '/statistiky',
  path: '/statistiky',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerNastaveniRoute = DispatcerNastaveniRouteImport.update({
  id: '/nastaveni',
  path: '/nastaveni',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerMapaRoute = DispatcerMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerKalendarRoute = DispatcerKalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerFakturaceRoute = DispatcerFakturaceRouteImport.update({
  id: '/fakturace',
  path: '/fakturace',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerCrmRoute = DispatcerCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerArchivRoute = DispatcerArchivRouteImport.update({
  id: '/archiv',
  path: '/archiv',
  getParentRoute: () => DispatcerRoute,
} as any)
const DispatcerAiPristupRoute = DispatcerAiPristupRouteImport.update({
  id: '/ai-pristup',
  path: '/ai-pristup',
  getParentRoute: () => DispatcerRoute,
} as any)
const RidicVendingIndexRoute = RidicVendingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RidicVendingRoute,
} as any)
const VendingNavstevyVisitIdRoute = VendingNavstevyVisitIdRouteImport.update({
  id: '/$visitId',
  path: '/$visitId',
  getParentRoute: () => VendingNavstevyRoute,
} as any)
const VendingLokaceLocationIdRoute = VendingLokaceLocationIdRouteImport.update({
  id: '/$locationId',
  path: '/$locationId',
  getParentRoute: () => VendingLokaceRoute,
} as any)
const RidicVendingVisitIdRoute = RidicVendingVisitIdRouteImport.update({
  id: '/$visitId',
  path: '/$visitId',
  getParentRoute: () => RidicVendingRoute,
} as any)
const RidicPodRideIdRoute = RidicPodRideIdRouteImport.update({
  id: '/pod/$rideId',
  path: '/pod/$rideId',
  getParentRoute: () => RidicRoute,
} as any)
const DispatcerZamestnanciEmployeeIdRoute =
  DispatcerZamestnanciEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => DispatcerZamestnanciRoute,
  } as any)
const DispatcerCrmContactIdRoute = DispatcerCrmContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => DispatcerCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dispatcer': typeof DispatcerRouteWithChildren
  '/dokoncit-registraci': typeof DokoncitRegistraciRoute
  '/jak-to-funguje': typeof JakToFungujeRoute
  '/mockup': typeof MockupRoute
  '/mockup-light': typeof MockupLightRoute
  '/objednat': typeof ObjednatRoute
  '/ochrana-soukromi': typeof OchranaSoukromiRoute
  '/platba-uspesna': typeof PlatbaUspesnaRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/ridic': typeof RidicRouteWithChildren
  '/vending': typeof VendingRouteWithChildren
  '/vending-portal': typeof VendingPortalRouteWithChildren
  '/zakaznik': typeof ZakaznikRouteWithChildren
  '/dispatcer/ai-pristup': typeof DispatcerAiPristupRoute
  '/dispatcer/archiv': typeof DispatcerArchivRoute
  '/dispatcer/crm': typeof DispatcerCrmRouteWithChildren
  '/dispatcer/fakturace': typeof DispatcerFakturaceRoute
  '/dispatcer/kalendar': typeof DispatcerKalendarRoute
  '/dispatcer/mapa': typeof DispatcerMapaRoute
  '/dispatcer/nastaveni': typeof DispatcerNastaveniRoute
  '/dispatcer/statistiky': typeof DispatcerStatistikyRoute
  '/dispatcer/tymy': typeof DispatcerTymyRoute
  '/dispatcer/uzivatele': typeof DispatcerUzivateleRoute
  '/dispatcer/zamestnanci': typeof DispatcerZamestnanciRouteWithChildren
  '/dispatcer/zasilky': typeof DispatcerZasilkyRoute
  '/hodnoceni/$token': typeof HodnoceniTokenRoute
  '/ridic/dostupnost': typeof RidicDostupnostRoute
  '/ridic/gps': typeof RidicGpsRoute
  '/ridic/profil': typeof RidicProfilRoute
  '/ridic/vending': typeof RidicVendingRouteWithChildren
  '/ridic/zakazky': typeof RidicZakazkyRoute
  '/sledovani/$token': typeof SledovaniTokenRoute
  '/vending/incidenty': typeof VendingIncidentyRoute
  '/vending/klienti': typeof VendingKlientiRoute
  '/vending/kpi': typeof VendingKpiRoute
  '/vending/lokace': typeof VendingLokaceRouteWithChildren
  '/vending/mapa': typeof VendingMapaRoute
  '/vending/navstevy': typeof VendingNavstevyRouteWithChildren
  '/vending/sablony': typeof VendingSablonyRoute
  '/zakaznik/faktury': typeof ZakaznikFakturyRoute
  '/zakaznik/nova-zasilka': typeof ZakaznikNovaZasilkaRoute
  '/zakaznik/profil': typeof ZakaznikProfilRoute
  '/zakaznik/sablony': typeof ZakaznikSablonyRoute
  '/zakaznik/uctenky': typeof ZakaznikUctenkyRoute
  '/zakaznik/zasilky': typeof ZakaznikZasilkyRoute
  '/dispatcer/': typeof DispatcerIndexRoute
  '/ridic/': typeof RidicIndexRoute
  '/vending-portal/': typeof VendingPortalIndexRoute
  '/vending/': typeof VendingIndexRoute
  '/zakaznik/': typeof ZakaznikIndexRoute
  '/dispatcer/crm/$contactId': typeof DispatcerCrmContactIdRoute
  '/dispatcer/zamestnanci/$employeeId': typeof DispatcerZamestnanciEmployeeIdRoute
  '/ridic/pod/$rideId': typeof RidicPodRideIdRoute
  '/ridic/vending/$visitId': typeof RidicVendingVisitIdRoute
  '/vending/lokace/$locationId': typeof VendingLokaceLocationIdRoute
  '/vending/navstevy/$visitId': typeof VendingNavstevyVisitIdRoute
  '/ridic/vending/': typeof RidicVendingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dokoncit-registraci': typeof DokoncitRegistraciRoute
  '/jak-to-funguje': typeof JakToFungujeRoute
  '/mockup': typeof MockupRoute
  '/mockup-light': typeof MockupLightRoute
  '/objednat': typeof ObjednatRoute
  '/ochrana-soukromi': typeof OchranaSoukromiRoute
  '/platba-uspesna': typeof PlatbaUspesnaRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/dispatcer/ai-pristup': typeof DispatcerAiPristupRoute
  '/dispatcer/archiv': typeof DispatcerArchivRoute
  '/dispatcer/crm': typeof DispatcerCrmRouteWithChildren
  '/dispatcer/fakturace': typeof DispatcerFakturaceRoute
  '/dispatcer/kalendar': typeof DispatcerKalendarRoute
  '/dispatcer/mapa': typeof DispatcerMapaRoute
  '/dispatcer/nastaveni': typeof DispatcerNastaveniRoute
  '/dispatcer/statistiky': typeof DispatcerStatistikyRoute
  '/dispatcer/tymy': typeof DispatcerTymyRoute
  '/dispatcer/uzivatele': typeof DispatcerUzivateleRoute
  '/dispatcer/zamestnanci': typeof DispatcerZamestnanciRouteWithChildren
  '/dispatcer/zasilky': typeof DispatcerZasilkyRoute
  '/hodnoceni/$token': typeof HodnoceniTokenRoute
  '/ridic/dostupnost': typeof RidicDostupnostRoute
  '/ridic/gps': typeof RidicGpsRoute
  '/ridic/profil': typeof RidicProfilRoute
  '/ridic/zakazky': typeof RidicZakazkyRoute
  '/sledovani/$token': typeof SledovaniTokenRoute
  '/vending/incidenty': typeof VendingIncidentyRoute
  '/vending/klienti': typeof VendingKlientiRoute
  '/vending/kpi': typeof VendingKpiRoute
  '/vending/lokace': typeof VendingLokaceRouteWithChildren
  '/vending/mapa': typeof VendingMapaRoute
  '/vending/navstevy': typeof VendingNavstevyRouteWithChildren
  '/vending/sablony': typeof VendingSablonyRoute
  '/zakaznik/faktury': typeof ZakaznikFakturyRoute
  '/zakaznik/nova-zasilka': typeof ZakaznikNovaZasilkaRoute
  '/zakaznik/profil': typeof ZakaznikProfilRoute
  '/zakaznik/sablony': typeof ZakaznikSablonyRoute
  '/zakaznik/uctenky': typeof ZakaznikUctenkyRoute
  '/zakaznik/zasilky': typeof ZakaznikZasilkyRoute
  '/dispatcer': typeof DispatcerIndexRoute
  '/ridic': typeof RidicIndexRoute
  '/vending-portal': typeof VendingPortalIndexRoute
  '/vending': typeof VendingIndexRoute
  '/zakaznik': typeof ZakaznikIndexRoute
  '/dispatcer/crm/$contactId': typeof DispatcerCrmContactIdRoute
  '/dispatcer/zamestnanci/$employeeId': typeof DispatcerZamestnanciEmployeeIdRoute
  '/ridic/pod/$rideId': typeof RidicPodRideIdRoute
  '/ridic/vending/$visitId': typeof RidicVendingVisitIdRoute
  '/vending/lokace/$locationId': typeof VendingLokaceLocationIdRoute
  '/vending/navstevy/$visitId': typeof VendingNavstevyVisitIdRoute
  '/ridic/vending': typeof RidicVendingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/dispatcer': typeof DispatcerRouteWithChildren
  '/dokoncit-registraci': typeof DokoncitRegistraciRoute
  '/jak-to-funguje': typeof JakToFungujeRoute
  '/mockup': typeof MockupRoute
  '/mockup-light': typeof MockupLightRoute
  '/objednat': typeof ObjednatRoute
  '/ochrana-soukromi': typeof OchranaSoukromiRoute
  '/platba-uspesna': typeof PlatbaUspesnaRoute
  '/prihlaseni': typeof PrihlaseniRoute
  '/registrace': typeof RegistraceRoute
  '/ridic': typeof RidicRouteWithChildren
  '/vending': typeof VendingRouteWithChildren
  '/vending-portal': typeof VendingPortalRouteWithChildren
  '/zakaznik': typeof ZakaznikRouteWithChildren
  '/dispatcer/ai-pristup': typeof DispatcerAiPristupRoute
  '/dispatcer/archiv': typeof DispatcerArchivRoute
  '/dispatcer/crm': typeof DispatcerCrmRouteWithChildren
  '/dispatcer/fakturace': typeof DispatcerFakturaceRoute
  '/dispatcer/kalendar': typeof DispatcerKalendarRoute
  '/dispatcer/mapa': typeof DispatcerMapaRoute
  '/dispatcer/nastaveni': typeof DispatcerNastaveniRoute
  '/dispatcer/statistiky': typeof DispatcerStatistikyRoute
  '/dispatcer/tymy': typeof DispatcerTymyRoute
  '/dispatcer/uzivatele': typeof DispatcerUzivateleRoute
  '/dispatcer/zamestnanci': typeof DispatcerZamestnanciRouteWithChildren
  '/dispatcer/zasilky': typeof DispatcerZasilkyRoute
  '/hodnoceni/$token': typeof HodnoceniTokenRoute
  '/ridic/dostupnost': typeof RidicDostupnostRoute
  '/ridic/gps': typeof RidicGpsRoute
  '/ridic/profil': typeof RidicProfilRoute
  '/ridic/vending': typeof RidicVendingRouteWithChildren
  '/ridic/zakazky': typeof RidicZakazkyRoute
  '/sledovani/$token': typeof SledovaniTokenRoute
  '/vending/incidenty': typeof VendingIncidentyRoute
  '/vending/klienti': typeof VendingKlientiRoute
  '/vending/kpi': typeof VendingKpiRoute
  '/vending/lokace': typeof VendingLokaceRouteWithChildren
  '/vending/mapa': typeof VendingMapaRoute
  '/vending/navstevy': typeof VendingNavstevyRouteWithChildren
  '/vending/sablony': typeof VendingSablonyRoute
  '/zakaznik/faktury': typeof ZakaznikFakturyRoute
  '/zakaznik/nova-zasilka': typeof ZakaznikNovaZasilkaRoute
  '/zakaznik/profil': typeof ZakaznikProfilRoute
  '/zakaznik/sablony': typeof ZakaznikSablonyRoute
  '/zakaznik/uctenky': typeof ZakaznikUctenkyRoute
  '/zakaznik/zasilky': typeof ZakaznikZasilkyRoute
  '/dispatcer/': typeof DispatcerIndexRoute
  '/ridic/': typeof RidicIndexRoute
  '/vending-portal/': typeof VendingPortalIndexRoute
  '/vending/': typeof VendingIndexRoute
  '/zakaznik/': typeof ZakaznikIndexRoute
  '/dispatcer/crm/$contactId': typeof DispatcerCrmContactIdRoute
  '/dispatcer/zamestnanci/$employeeId': typeof DispatcerZamestnanciEmployeeIdRoute
  '/ridic/pod/$rideId': typeof RidicPodRideIdRoute
  '/ridic/vending/$visitId': typeof RidicVendingVisitIdRoute
  '/vending/lokace/$locationId': typeof VendingLokaceLocationIdRoute
  '/vending/navstevy/$visitId': typeof VendingNavstevyVisitIdRoute
  '/ridic/vending/': typeof RidicVendingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/dispatcer'
    | '/dokoncit-registraci'
    | '/jak-to-funguje'
    | '/mockup'
    | '/mockup-light'
    | '/objednat'
    | '/ochrana-soukromi'
    | '/platba-uspesna'
    | '/prihlaseni'
    | '/registrace'
    | '/ridic'
    | '/vending'
    | '/vending-portal'
    | '/zakaznik'
    | '/dispatcer/ai-pristup'
    | '/dispatcer/archiv'
    | '/dispatcer/crm'
    | '/dispatcer/fakturace'
    | '/dispatcer/kalendar'
    | '/dispatcer/mapa'
    | '/dispatcer/nastaveni'
    | '/dispatcer/statistiky'
    | '/dispatcer/tymy'
    | '/dispatcer/uzivatele'
    | '/dispatcer/zamestnanci'
    | '/dispatcer/zasilky'
    | '/hodnoceni/$token'
    | '/ridic/dostupnost'
    | '/ridic/gps'
    | '/ridic/profil'
    | '/ridic/vending'
    | '/ridic/zakazky'
    | '/sledovani/$token'
    | '/vending/incidenty'
    | '/vending/klienti'
    | '/vending/kpi'
    | '/vending/lokace'
    | '/vending/mapa'
    | '/vending/navstevy'
    | '/vending/sablony'
    | '/zakaznik/faktury'
    | '/zakaznik/nova-zasilka'
    | '/zakaznik/profil'
    | '/zakaznik/sablony'
    | '/zakaznik/uctenky'
    | '/zakaznik/zasilky'
    | '/dispatcer/'
    | '/ridic/'
    | '/vending-portal/'
    | '/vending/'
    | '/zakaznik/'
    | '/dispatcer/crm/$contactId'
    | '/dispatcer/zamestnanci/$employeeId'
    | '/ridic/pod/$rideId'
    | '/ridic/vending/$visitId'
    | '/vending/lokace/$locationId'
    | '/vending/navstevy/$visitId'
    | '/ridic/vending/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/dokoncit-registraci'
    | '/jak-to-funguje'
    | '/mockup'
    | '/mockup-light'
    | '/objednat'
    | '/ochrana-soukromi'
    | '/platba-uspesna'
    | '/prihlaseni'
    | '/registrace'
    | '/dispatcer/ai-pristup'
    | '/dispatcer/archiv'
    | '/dispatcer/crm'
    | '/dispatcer/fakturace'
    | '/dispatcer/kalendar'
    | '/dispatcer/mapa'
    | '/dispatcer/nastaveni'
    | '/dispatcer/statistiky'
    | '/dispatcer/tymy'
    | '/dispatcer/uzivatele'
    | '/dispatcer/zamestnanci'
    | '/dispatcer/zasilky'
    | '/hodnoceni/$token'
    | '/ridic/dostupnost'
    | '/ridic/gps'
    | '/ridic/profil'
    | '/ridic/zakazky'
    | '/sledovani/$token'
    | '/vending/incidenty'
    | '/vending/klienti'
    | '/vending/kpi'
    | '/vending/lokace'
    | '/vending/mapa'
    | '/vending/navstevy'
    | '/vending/sablony'
    | '/zakaznik/faktury'
    | '/zakaznik/nova-zasilka'
    | '/zakaznik/profil'
    | '/zakaznik/sablony'
    | '/zakaznik/uctenky'
    | '/zakaznik/zasilky'
    | '/dispatcer'
    | '/ridic'
    | '/vending-portal'
    | '/vending'
    | '/zakaznik'
    | '/dispatcer/crm/$contactId'
    | '/dispatcer/zamestnanci/$employeeId'
    | '/ridic/pod/$rideId'
    | '/ridic/vending/$visitId'
    | '/vending/lokace/$locationId'
    | '/vending/navstevy/$visitId'
    | '/ridic/vending'
  id:
    | '__root__'
    | '/'
    | '/admin-setup'
    | '/dispatcer'
    | '/dokoncit-registraci'
    | '/jak-to-funguje'
    | '/mockup'
    | '/mockup-light'
    | '/objednat'
    | '/ochrana-soukromi'
    | '/platba-uspesna'
    | '/prihlaseni'
    | '/registrace'
    | '/ridic'
    | '/vending'
    | '/vending-portal'
    | '/zakaznik'
    | '/dispatcer/ai-pristup'
    | '/dispatcer/archiv'
    | '/dispatcer/crm'
    | '/dispatcer/fakturace'
    | '/dispatcer/kalendar'
    | '/dispatcer/mapa'
    | '/dispatcer/nastaveni'
    | '/dispatcer/statistiky'
    | '/dispatcer/tymy'
    | '/dispatcer/uzivatele'
    | '/dispatcer/zamestnanci'
    | '/dispatcer/zasilky'
    | '/hodnoceni/$token'
    | '/ridic/dostupnost'
    | '/ridic/gps'
    | '/ridic/profil'
    | '/ridic/vending'
    | '/ridic/zakazky'
    | '/sledovani/$token'
    | '/vending/incidenty'
    | '/vending/klienti'
    | '/vending/kpi'
    | '/vending/lokace'
    | '/vending/mapa'
    | '/vending/navstevy'
    | '/vending/sablony'
    | '/zakaznik/faktury'
    | '/zakaznik/nova-zasilka'
    | '/zakaznik/profil'
    | '/zakaznik/sablony'
    | '/zakaznik/uctenky'
    | '/zakaznik/zasilky'
    | '/dispatcer/'
    | '/ridic/'
    | '/vending-portal/'
    | '/vending/'
    | '/zakaznik/'
    | '/dispatcer/crm/$contactId'
    | '/dispatcer/zamestnanci/$employeeId'
    | '/ridic/pod/$rideId'
    | '/ridic/vending/$visitId'
    | '/vending/lokace/$locationId'
    | '/vending/navstevy/$visitId'
    | '/ridic/vending/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSetupRoute: typeof AdminSetupRoute
  DispatcerRoute: typeof DispatcerRouteWithChildren
  DokoncitRegistraciRoute: typeof DokoncitRegistraciRoute
  JakToFungujeRoute: typeof JakToFungujeRoute
  MockupRoute: typeof MockupRoute
  MockupLightRoute: typeof MockupLightRoute
  ObjednatRoute: typeof ObjednatRoute
  OchranaSoukromiRoute: typeof OchranaSoukromiRoute
  PlatbaUspesnaRoute: typeof PlatbaUspesnaRoute
  PrihlaseniRoute: typeof PrihlaseniRoute
  RegistraceRoute: typeof RegistraceRoute
  RidicRoute: typeof RidicRouteWithChildren
  VendingRoute: typeof VendingRouteWithChildren
  VendingPortalRoute: typeof VendingPortalRouteWithChildren
  ZakaznikRoute: typeof ZakaznikRouteWithChildren
  HodnoceniTokenRoute: typeof HodnoceniTokenRoute
  SledovaniTokenRoute: typeof SledovaniTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zakaznik': {
      id: '/zakaznik'
      path: '/zakaznik'
      fullPath: '/zakaznik'
      preLoaderRoute: typeof ZakaznikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vending-portal': {
      id: '/vending-portal'
      path: '/vending-portal'
      fullPath: '/vending-portal'
      preLoaderRoute: typeof VendingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vending': {
      id: '/vending'
      path: '/vending'
      fullPath: '/vending'
      preLoaderRoute: typeof VendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ridic': {
      id: '/ridic'
      path: '/ridic'
      fullPath: '/ridic'
      preLoaderRoute: typeof RidicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrace': {
      id: '/registrace'
      path: '/registrace'
      fullPath: '/registrace'
      preLoaderRoute: typeof RegistraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prihlaseni': {
      id: '/prihlaseni'
      path: '/prihlaseni'
      fullPath: '/prihlaseni'
      preLoaderRoute: typeof PrihlaseniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platba-uspesna': {
      id: '/platba-uspesna'
      path: '/platba-uspesna'
      fullPath: '/platba-uspesna'
      preLoaderRoute: typeof PlatbaUspesnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ochrana-soukromi': {
      id: '/ochrana-soukromi'
      path: '/ochrana-soukromi'
      fullPath: '/ochrana-soukromi'
      preLoaderRoute: typeof OchranaSoukromiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objednat': {
      id: '/objednat'
      path: '/objednat'
      fullPath: '/objednat'
      preLoaderRoute: typeof ObjednatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup-light': {
      id: '/mockup-light'
      path: '/mockup-light'
      fullPath: '/mockup-light'
      preLoaderRoute: typeof MockupLightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup': {
      id: '/mockup'
      path: '/mockup'
      fullPath: '/mockup'
      preLoaderRoute: typeof MockupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jak-to-funguje': {
      id: '/jak-to-funguje'
      path: '/jak-to-funguje'
      fullPath: '/jak-to-funguje'
      preLoaderRoute: typeof JakToFungujeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokoncit-registraci': {
      id: '/dokoncit-registraci'
      path: '/dokoncit-registraci'
      fullPath: '/dokoncit-registraci'
      preLoaderRoute: typeof DokoncitRegistraciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatcer': {
      id: '/dispatcer'
      path: '/dispatcer'
      fullPath: '/dispatcer'
      preLoaderRoute: typeof DispatcerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakaznik/': {
      id: '/zakaznik/'
      path: '/'
      fullPath: '/zakaznik/'
      preLoaderRoute: typeof ZakaznikIndexRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/vending/': {
      id: '/vending/'
      path: '/'
      fullPath: '/vending/'
      preLoaderRoute: typeof VendingIndexRouteImport
      parentRoute: typeof VendingRoute
    }
    '/vending-portal/': {
      id: '/vending-portal/'
      path: '/'
      fullPath: '/vending-portal/'
      preLoaderRoute: typeof VendingPortalIndexRouteImport
      parentRoute: typeof VendingPortalRoute
    }
    '/ridic/': {
      id: '/ridic/'
      path: '/'
      fullPath: '/ridic/'
      preLoaderRoute: typeof RidicIndexRouteImport
      parentRoute: typeof RidicRoute
    }
    '/dispatcer/': {
      id: '/dispatcer/'
      path: '/'
      fullPath: '/dispatcer/'
      preLoaderRoute: typeof DispatcerIndexRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/zakaznik/zasilky': {
      id: '/zakaznik/zasilky'
      path: '/zasilky'
      fullPath: '/zakaznik/zasilky'
      preLoaderRoute: typeof ZakaznikZasilkyRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/uctenky': {
      id: '/zakaznik/uctenky'
      path: '/uctenky'
      fullPath: '/zakaznik/uctenky'
      preLoaderRoute: typeof ZakaznikUctenkyRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/sablony': {
      id: '/zakaznik/sablony'
      path: '/sablony'
      fullPath: '/zakaznik/sablony'
      preLoaderRoute: typeof ZakaznikSablonyRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/profil': {
      id: '/zakaznik/profil'
      path: '/profil'
      fullPath: '/zakaznik/profil'
      preLoaderRoute: typeof ZakaznikProfilRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/nova-zasilka': {
      id: '/zakaznik/nova-zasilka'
      path: '/nova-zasilka'
      fullPath: '/zakaznik/nova-zasilka'
      preLoaderRoute: typeof ZakaznikNovaZasilkaRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/zakaznik/faktury': {
      id: '/zakaznik/faktury'
      path: '/faktury'
      fullPath: '/zakaznik/faktury'
      preLoaderRoute: typeof ZakaznikFakturyRouteImport
      parentRoute: typeof ZakaznikRoute
    }
    '/vending/sablony': {
      id: '/vending/sablony'
      path: '/sablony'
      fullPath: '/vending/sablony'
      preLoaderRoute: typeof VendingSablonyRouteImport
      parentRoute: typeof VendingRoute
    }
    '/vending/navstevy': {
      id: '/vending/navstevy'
      path: '/navstevy'
      fullPath: '/vending/navstevy'
      preLoaderRoute: typeof VendingNavstevyRouteImport
      parentRoute: typeof VendingRoute
    }
    '/vending/mapa': {
      id: '/vending/mapa'
      path: '/mapa'
      fullPath: '/vending/mapa'
      preLoaderRoute: typeof VendingMapaRouteImport
      parentRoute: typeof VendingRoute
    }
    '/vending/lokace': {
      id: '/vending/lokace'
      path: '/lokace'
      fullPath: '/vending/lokace'
      preLoaderRoute: typeof VendingLokaceRouteImport
      parentRoute: typeof VendingRoute
    }
    '/vending/kpi': {
      id: '/vending/kpi'
      path: '/kpi'
      fullPath: '/vending/kpi'
      preLoaderRoute: typeof VendingKpiRouteImport
      parentRoute: typeof VendingRoute
    }
    '/vending/klienti': {
      id: '/vending/klienti'
      path: '/klienti'
      fullPath: '/vending/klienti'
      preLoaderRoute: typeof VendingKlientiRouteImport
      parentRoute: typeof VendingRoute
    }
    '/vending/incidenty': {
      id: '/vending/incidenty'
      path: '/incidenty'
      fullPath: '/vending/incidenty'
      preLoaderRoute: typeof VendingIncidentyRouteImport
      parentRoute: typeof VendingRoute
    }
    '/sledovani/$token': {
      id: '/sledovani/$token'
      path: '/sledovani/$token'
      fullPath: '/sledovani/$token'
      preLoaderRoute: typeof SledovaniTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ridic/zakazky': {
      id: '/ridic/zakazky'
      path: '/zakazky'
      fullPath: '/ridic/zakazky'
      preLoaderRoute: typeof RidicZakazkyRouteImport
      parentRoute: typeof RidicRoute
    }
    '/ridic/vending': {
      id: '/ridic/vending'
      path: '/vending'
      fullPath: '/ridic/vending'
      preLoaderRoute: typeof RidicVendingRouteImport
      parentRoute: typeof RidicRoute
    }
    '/ridic/profil': {
      id: '/ridic/profil'
      path: '/profil'
      fullPath: '/ridic/profil'
      preLoaderRoute: typeof RidicProfilRouteImport
      parentRoute: typeof RidicRoute
    }
    '/ridic/gps': {
      id: '/ridic/gps'
      path: '/gps'
      fullPath: '/ridic/gps'
      preLoaderRoute: typeof RidicGpsRouteImport
      parentRoute: typeof RidicRoute
    }
    '/ridic/dostupnost': {
      id: '/ridic/dostupnost'
      path: '/dostupnost'
      fullPath: '/ridic/dostupnost'
      preLoaderRoute: typeof RidicDostupnostRouteImport
      parentRoute: typeof RidicRoute
    }
    '/hodnoceni/$token': {
      id: '/hodnoceni/$token'
      path: '/hodnoceni/$token'
      fullPath: '/hodnoceni/$token'
      preLoaderRoute: typeof HodnoceniTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatcer/zasilky': {
      id: '/dispatcer/zasilky'
      path: '/zasilky'
      fullPath: '/dispatcer/zasilky'
      preLoaderRoute: typeof DispatcerZasilkyRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/zamestnanci': {
      id: '/dispatcer/zamestnanci'
      path: '/zamestnanci'
      fullPath: '/dispatcer/zamestnanci'
      preLoaderRoute: typeof DispatcerZamestnanciRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/uzivatele': {
      id: '/dispatcer/uzivatele'
      path: '/uzivatele'
      fullPath: '/dispatcer/uzivatele'
      preLoaderRoute: typeof DispatcerUzivateleRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/tymy': {
      id: '/dispatcer/tymy'
      path: '/tymy'
      fullPath: '/dispatcer/tymy'
      preLoaderRoute: typeof DispatcerTymyRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/statistiky': {
      id: '/dispatcer/statistiky'
      path: '/statistiky'
      fullPath: '/dispatcer/statistiky'
      preLoaderRoute: typeof DispatcerStatistikyRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/nastaveni': {
      id: '/dispatcer/nastaveni'
      path: '/nastaveni'
      fullPath: '/dispatcer/nastaveni'
      preLoaderRoute: typeof DispatcerNastaveniRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/mapa': {
      id: '/dispatcer/mapa'
      path: '/mapa'
      fullPath: '/dispatcer/mapa'
      preLoaderRoute: typeof DispatcerMapaRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/kalendar': {
      id: '/dispatcer/kalendar'
      path: '/kalendar'
      fullPath: '/dispatcer/kalendar'
      preLoaderRoute: typeof DispatcerKalendarRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/fakturace': {
      id: '/dispatcer/fakturace'
      path: '/fakturace'
      fullPath: '/dispatcer/fakturace'
      preLoaderRoute: typeof DispatcerFakturaceRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/crm': {
      id: '/dispatcer/crm'
      path: '/crm'
      fullPath: '/dispatcer/crm'
      preLoaderRoute: typeof DispatcerCrmRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/archiv': {
      id: '/dispatcer/archiv'
      path: '/archiv'
      fullPath: '/dispatcer/archiv'
      preLoaderRoute: typeof DispatcerArchivRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/dispatcer/ai-pristup': {
      id: '/dispatcer/ai-pristup'
      path: '/ai-pristup'
      fullPath: '/dispatcer/ai-pristup'
      preLoaderRoute: typeof DispatcerAiPristupRouteImport
      parentRoute: typeof DispatcerRoute
    }
    '/ridic/vending/': {
      id: '/ridic/vending/'
      path: '/'
      fullPath: '/ridic/vending/'
      preLoaderRoute: typeof RidicVendingIndexRouteImport
      parentRoute: typeof RidicVendingRoute
    }
    '/vending/navstevy/$visitId': {
      id: '/vending/navstevy/$visitId'
      path: '/$visitId'
      fullPath: '/vending/navstevy/$visitId'
      preLoaderRoute: typeof VendingNavstevyVisitIdRouteImport
      parentRoute: typeof VendingNavstevyRoute
    }
    '/vending/lokace/$locationId': {
      id: '/vending/lokace/$locationId'
      path: '/$locationId'
      fullPath: '/vending/lokace/$locationId'
      preLoaderRoute: typeof VendingLokaceLocationIdRouteImport
      parentRoute: typeof VendingLokaceRoute
    }
    '/ridic/vending/$visitId': {
      id: '/ridic/vending/$visitId'
      path: '/$visitId'
      fullPath: '/ridic/vending/$visitId'
      preLoaderRoute: typeof RidicVendingVisitIdRouteImport
      parentRoute: typeof RidicVendingRoute
    }
    '/ridic/pod/$rideId': {
      id: '/ridic/pod/$rideId'
      path: '/pod/$rideId'
      fullPath: '/ridic/pod/$rideId'
      preLoaderRoute: typeof RidicPodRideIdRouteImport
      parentRoute: typeof RidicRoute
    }
    '/dispatcer/zamestnanci/$employeeId': {
      id: '/dispatcer/zamestnanci/$employeeId'
      path: '/$employeeId'
      fullPath: '/dispatcer/zamestnanci/$employeeId'
      preLoaderRoute: typeof DispatcerZamestnanciEmployeeIdRouteImport
      parentRoute: typeof DispatcerZamestnanciRoute
    }
    '/dispatcer/crm/$contactId': {
      id: '/dispatcer/crm/$contactId'
      path: '/$contactId'
      fullPath: '/dispatcer/crm/$contactId'
      preLoaderRoute: typeof DispatcerCrmContactIdRouteImport
      parentRoute: typeof DispatcerCrmRoute
    }
  }
}

interface DispatcerCrmRouteChildren {
  DispatcerCrmContactIdRoute: typeof DispatcerCrmContactIdRoute
}

const DispatcerCrmRouteChildren: DispatcerCrmRouteChildren = {
  DispatcerCrmContactIdRoute: DispatcerCrmContactIdRoute,
}

const DispatcerCrmRouteWithChildren = DispatcerCrmRoute._addFileChildren(
  DispatcerCrmRouteChildren,
)

interface DispatcerZamestnanciRouteChildren {
  DispatcerZamestnanciEmployeeIdRoute: typeof DispatcerZamestnanciEmployeeIdRoute
}

const DispatcerZamestnanciRouteChildren: DispatcerZamestnanciRouteChildren = {
  DispatcerZamestnanciEmployeeIdRoute: DispatcerZamestnanciEmployeeIdRoute,
}

const DispatcerZamestnanciRouteWithChildren =
  DispatcerZamestnanciRoute._addFileChildren(DispatcerZamestnanciRouteChildren)

interface DispatcerRouteChildren {
  DispatcerAiPristupRoute: typeof DispatcerAiPristupRoute
  DispatcerArchivRoute: typeof DispatcerArchivRoute
  DispatcerCrmRoute: typeof DispatcerCrmRouteWithChildren
  DispatcerFakturaceRoute: typeof DispatcerFakturaceRoute
  DispatcerKalendarRoute: typeof DispatcerKalendarRoute
  DispatcerMapaRoute: typeof DispatcerMapaRoute
  DispatcerNastaveniRoute: typeof DispatcerNastaveniRoute
  DispatcerStatistikyRoute: typeof DispatcerStatistikyRoute
  DispatcerTymyRoute: typeof DispatcerTymyRoute
  DispatcerUzivateleRoute: typeof DispatcerUzivateleRoute
  DispatcerZamestnanciRoute: typeof DispatcerZamestnanciRouteWithChildren
  DispatcerZasilkyRoute: typeof DispatcerZasilkyRoute
  DispatcerIndexRoute: typeof DispatcerIndexRoute
}

const DispatcerRouteChildren: DispatcerRouteChildren = {
  DispatcerAiPristupRoute: DispatcerAiPristupRoute,
  DispatcerArchivRoute: DispatcerArchivRoute,
  DispatcerCrmRoute: DispatcerCrmRouteWithChildren,
  DispatcerFakturaceRoute: DispatcerFakturaceRoute,
  DispatcerKalendarRoute: DispatcerKalendarRoute,
  DispatcerMapaRoute: DispatcerMapaRoute,
  DispatcerNastaveniRoute: DispatcerNastaveniRoute,
  DispatcerStatistikyRoute: DispatcerStatistikyRoute,
  DispatcerTymyRoute: DispatcerTymyRoute,
  DispatcerUzivateleRoute: DispatcerUzivateleRoute,
  DispatcerZamestnanciRoute: DispatcerZamestnanciRouteWithChildren,
  DispatcerZasilkyRoute: DispatcerZasilkyRoute,
  DispatcerIndexRoute: DispatcerIndexRoute,
}

const DispatcerRouteWithChildren = DispatcerRoute._addFileChildren(
  DispatcerRouteChildren,
)

interface RidicVendingRouteChildren {
  RidicVendingVisitIdRoute: typeof RidicVendingVisitIdRoute
  RidicVendingIndexRoute: typeof RidicVendingIndexRoute
}

const RidicVendingRouteChildren: RidicVendingRouteChildren = {
  RidicVendingVisitIdRoute: RidicVendingVisitIdRoute,
  RidicVendingIndexRoute: RidicVendingIndexRoute,
}

const RidicVendingRouteWithChildren = RidicVendingRoute._addFileChildren(
  RidicVendingRouteChildren,
)

interface RidicRouteChildren {
  RidicDostupnostRoute: typeof RidicDostupnostRoute
  RidicGpsRoute: typeof RidicGpsRoute
  RidicProfilRoute: typeof RidicProfilRoute
  RidicVendingRoute: typeof RidicVendingRouteWithChildren
  RidicZakazkyRoute: typeof RidicZakazkyRoute
  RidicIndexRoute: typeof RidicIndexRoute
  RidicPodRideIdRoute: typeof RidicPodRideIdRoute
}

const RidicRouteChildren: RidicRouteChildren = {
  RidicDostupnostRoute: RidicDostupnostRoute,
  RidicGpsRoute: RidicGpsRoute,
  RidicProfilRoute: RidicProfilRoute,
  RidicVendingRoute: RidicVendingRouteWithChildren,
  RidicZakazkyRoute: RidicZakazkyRoute,
  RidicIndexRoute: RidicIndexRoute,
  RidicPodRideIdRoute: RidicPodRideIdRoute,
}

const RidicRouteWithChildren = RidicRoute._addFileChildren(RidicRouteChildren)

interface VendingLokaceRouteChildren {
  VendingLokaceLocationIdRoute: typeof VendingLokaceLocationIdRoute
}

const VendingLokaceRouteChildren: VendingLokaceRouteChildren = {
  VendingLokaceLocationIdRoute: VendingLokaceLocationIdRoute,
}

const VendingLokaceRouteWithChildren = VendingLokaceRoute._addFileChildren(
  VendingLokaceRouteChildren,
)

interface VendingNavstevyRouteChildren {
  VendingNavstevyVisitIdRoute: typeof VendingNavstevyVisitIdRoute
}

const VendingNavstevyRouteChildren: VendingNavstevyRouteChildren = {
  VendingNavstevyVisitIdRoute: VendingNavstevyVisitIdRoute,
}

const VendingNavstevyRouteWithChildren = VendingNavstevyRoute._addFileChildren(
  VendingNavstevyRouteChildren,
)

interface VendingRouteChildren {
  VendingIncidentyRoute: typeof VendingIncidentyRoute
  VendingKlientiRoute: typeof VendingKlientiRoute
  VendingKpiRoute: typeof VendingKpiRoute
  VendingLokaceRoute: typeof VendingLokaceRouteWithChildren
  VendingMapaRoute: typeof VendingMapaRoute
  VendingNavstevyRoute: typeof VendingNavstevyRouteWithChildren
  VendingSablonyRoute: typeof VendingSablonyRoute
  VendingIndexRoute: typeof VendingIndexRoute
}

const VendingRouteChildren: VendingRouteChildren = {
  VendingIncidentyRoute: VendingIncidentyRoute,
  VendingKlientiRoute: VendingKlientiRoute,
  VendingKpiRoute: VendingKpiRoute,
  VendingLokaceRoute: VendingLokaceRouteWithChildren,
  VendingMapaRoute: VendingMapaRoute,
  VendingNavstevyRoute: VendingNavstevyRouteWithChildren,
  VendingSablonyRoute: VendingSablonyRoute,
  VendingIndexRoute: VendingIndexRoute,
}

const VendingRouteWithChildren =
  VendingRoute._addFileChildren(VendingRouteChildren)

interface VendingPortalRouteChildren {
  VendingPortalIndexRoute: typeof VendingPortalIndexRoute
}

const VendingPortalRouteChildren: VendingPortalRouteChildren = {
  VendingPortalIndexRoute: VendingPortalIndexRoute,
}

const VendingPortalRouteWithChildren = VendingPortalRoute._addFileChildren(
  VendingPortalRouteChildren,
)

interface ZakaznikRouteChildren {
  ZakaznikFakturyRoute: typeof ZakaznikFakturyRoute
  ZakaznikNovaZasilkaRoute: typeof ZakaznikNovaZasilkaRoute
  ZakaznikProfilRoute: typeof ZakaznikProfilRoute
  ZakaznikSablonyRoute: typeof ZakaznikSablonyRoute
  ZakaznikUctenkyRoute: typeof ZakaznikUctenkyRoute
  ZakaznikZasilkyRoute: typeof ZakaznikZasilkyRoute
  ZakaznikIndexRoute: typeof ZakaznikIndexRoute
}

const ZakaznikRouteChildren: ZakaznikRouteChildren = {
  ZakaznikFakturyRoute: ZakaznikFakturyRoute,
  ZakaznikNovaZasilkaRoute: ZakaznikNovaZasilkaRoute,
  ZakaznikProfilRoute: ZakaznikProfilRoute,
  ZakaznikSablonyRoute: ZakaznikSablonyRoute,
  ZakaznikUctenkyRoute: ZakaznikUctenkyRoute,
  ZakaznikZasilkyRoute: ZakaznikZasilkyRoute,
  ZakaznikIndexRoute: ZakaznikIndexRoute,
}

const ZakaznikRouteWithChildren = ZakaznikRoute._addFileChildren(
  ZakaznikRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSetupRoute: AdminSetupRoute,
  DispatcerRoute: DispatcerRouteWithChildren,
  DokoncitRegistraciRoute: DokoncitRegistraciRoute,
  JakToFungujeRoute: JakToFungujeRoute,
  MockupRoute: MockupRoute,
  MockupLightRoute: MockupLightRoute,
  ObjednatRoute: ObjednatRoute,
  OchranaSoukromiRoute: OchranaSoukromiRoute,
  PlatbaUspesnaRoute: PlatbaUspesnaRoute,
  PrihlaseniRoute: PrihlaseniRoute,
  RegistraceRoute: RegistraceRoute,
  RidicRoute: RidicRouteWithChildren,
  VendingRoute: VendingRouteWithChildren,
  VendingPortalRoute: VendingPortalRouteWithChildren,
  ZakaznikRoute: ZakaznikRouteWithChildren,
  HodnoceniTokenRoute: HodnoceniTokenRoute,
  SledovaniTokenRoute: SledovaniTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
